### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by suke27** [krshrimali/Image-Quality---BRISQUE#1]
Hi, I try to run your code, but I found for some images it output score less than 0

 brisqueFeatures length 36 score in images/style transfer/landscape/02_johnson//07.jpg is given by:-3.44121

 brisqueFeatures length 36 score in images/style transfer/landscape/02_johnson//08.jpg is given by:-0.927788

 brisqueFeatures length 36 score in images/style transfer/landscape/02_johnson//09.jpg is given by:3.78625

is it a normal case?

**Comment by krshrimali** [comment]
@suke27  - I'll let you know the updates. The repository has been made private for now, you'll soon receive a link for the better.
